# @package _global_

# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

io:
  input_filename: null
  input_dir: null
  input_trajectory_dir: null
  output_dir: null
  # Spatial reference to use to override the one from input las.
  spatial_reference: EPSG:2154

tile_geometry:
  tile_coord_scale: 1000  # coords in tile names are in km
  tile_width: 1000

commons: 
  filter_date:
    deviation_days: 0
  class_count:
    keep_classes: [1, 2, 3, 4, 5, 6, 9, 17, 18, 64, 66, 67]
    
preprocessing:
  filter:
    dimension: Classification
    keep_values: [1, 2, 3, 4, 5, 9, 17, 64, 67]   # Classes to keep 
  filter_outlier:
    mean_k: 5
    multiplier: 10
  normalize:
    min_height_filter: -3
    height_filter: 80
  trajectory:
    nodata: 0

pad_profile:
  cos_theta:
    scanning_angle: True
    limit_N_points: 400
    limit_flight_agl: 800
  compute_ni_n:
    z0: 0.0
    dz: 1.0
    nlayers: 60
    dz_low: 0.5
    nlayers_low: 4
    ground_margin: 0.1
  compute_cover:
    cover_type: "all"
    height_cover: 2.0
    use_cover: True
  compute_pad:
    G: 0.5
    omega: 1
    keep_values: [2, 3, 4, 5, 9]
  create_raster:
    origin_x: 98029.75
    origin_y: 6045536.75
    resolution_factor: 10.0

dtm:
  download:
    resolution: 0.5 # Pixel size in metres
    dtm_layer : "IGNF_LIDAR-HD_MNT_ELEVATION.ELEVATIONGRIDCOVERAGE.LAMB93"
    timeout: 60
    epsg: 2154
  input_filename: null
  output_subfolder: "DTM"
  nodata_value: -9999  # h_abg value assigned to points on NoData DTM pixels

hydra:
  output_subdir: null
  run:
    dir: .